version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./secrets/.env.local
    ports:
      - 5432:5432
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    command: python ./app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/
    ports:
      - "8000:8000"
    env_file:
      - ./secrets/.env.local
    depends_on:
      - db
volumes:
  postgres_data:
