FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /home/
COPY requirements.txt /home/
RUN pip install -r requirements.txt
COPY . /home/
WORKDIR /home/app
ENTRYPOINT ["sh","/home/app/docker-entrypoint.local.sh"]
